# Generated by Django 6.1 on 2026-09-01 21:11

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.users.validators.validate_avatar_file]),
        ),
    ]
