# Generated by Django 6.1 on 2026-08-13 00:58

import apps.catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', validators=[apps.catalog.validators.validate_cover_file])),
                ('epub_file', models.FileField(upload_to='books/epub/', validators=[django.core.validators.FileExtensionValidator(['epub']), apps.catalog.validators.validate_book_file_size])),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.catalog.validators.validate_book_file_size])),
                ('fb2_file', models.FileField(blank=True, null=True, upload_to='books/fb2/', validators=[django.core.validators.FileExtensionValidator(['fb2']), apps.catalog.validators.validate_book_file_size])),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(db_table='book_authors', related_name='books', to='catalog.author')),
                ('genres', models.ManyToManyField(db_table='book_genres', related_name='books', to='catalog.genre')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='books_is_acti_a3aae1_idx'), models.Index(fields=['isbn'], name='books_isbn_ce4a1a_idx'), models.Index(fields=['created_at'], name='books_created_a6d93f_idx'), models.Index(fields=['price'], name='books_price_89e2a6_idx')],
            },
        ),
    ]
