# Generated by Django 6.1 on 2026-09-28 21:57

import apps.catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_description_cover_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=models.FileField(upload_to='books/epub/', validators=[django.core.validators.FileExtensionValidator(['epub']), apps.catalog.validators.validate_book_file_size, apps.catalog.validators.validate_epub_file]),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_file',
            field=models.FileField(blank=True, null=True, upload_to='books/fb2/', validators=[django.core.validators.FileExtensionValidator(['fb2']), apps.catalog.validators.validate_book_file_size, apps.catalog.validators.validate_fb2_file]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.catalog.validators.validate_book_file_size, apps.catalog.validators.validate_pdf_file]),
        ),
    ]
