# Generated by Django 6.1 on 2026-08-30 14:14

import apps.reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=2000, validators=[apps.reviews.validators.validate_review_text_length]),
        ),
    ]
